language: node_js

node_js:
  - 13

services:
  - docker

install:
  - npm install

script:
  - npm test

after_success:
  - docker build . -t "nl2go/hetzner-robot-api-mock:$TRAVIS_BRANCH"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "nl2go/hetzner-robot-api-mock:$TRAVIS_BRANCH"
